# Generated by Django 3.0.7 on 2022-02-21 09:25

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', validators=[app.validators.validate_image], verbose_name='')),
                ('video', models.FileField(upload_to='', validators=[app.validators.validate_video], verbose_name='')),
            ],
        ),
    ]
